apiVersion: v1
kind: Service
metadata:
  name: greet-api
  labels:
    app: greet-api
spec:
  ports:
    - port: 8080
  selector:
    app: greet-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-api
  labels:
    app: greet-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greet-api
  template:
    metadata:
      labels:
        app: greet-api
    spec:
      containers:
        - name: greet-api
          image: greet/api:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
